
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Employee Productivity Tracking System Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment for deployment

  BucketName:
    Type: String
    Description: Name of the S3 bucket for screenshots
    Default: employee-productivity-screenshots

Resources:
  # S3 Bucket for storing screenshots
  ScreenshotBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${BucketName}-${Environment}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['Content-Type', 'Authorization']
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ['*']
            MaxAge: 3000

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:InvokeModel'
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: !Sub '${ScreenshotBucket.Arn}/*'

  # Visual Analysis Lambda
  VisualAnalysisLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-visual-analysis-${Environment}'
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import json
          import base64
          
          def get_bedrock_client():
              return boto3.client('bedrock-runtime', region_name='us-east-1')
          
          def analyze_image_with_nova(image_data, bedrock):
              try:
                  body = json.dumps({
                      "inputImage": image_data,
                      "imageGenerationConfig": {
                          "numberOfImages": 1,
                          "quality": "standard",
                          "cfgScale": 7.5
                      },
                      "prompt": """Analyze this screenshot and provide:
                          1. All visible applications and windows
                          2. UI elements and their states
                          3. Any visible timestamps
                          4. User interactions visible
                          5. Type of work being performed"""
                  })
          
                  response = bedrock.invoke_model(
                      modelId="us.amazon.nova-lite-v1:0",
                      body=body
                  )
                  
                  return json.loads(response.get('body').read())
              except Exception as e:
                  print(f"Error in analyze_image_with_nova: {str(e)}")
                  raise
          
          def lambda_handler(event, context):
              try:
                  print("Starting visual analysis process")
                  print(f"Event: {json.dumps(event)}")
                  
                  # Extract image data from input
                  input_data = json.loads(event.get('input', '{}'))
                  image_data = input_data.get('image_data')
                  
                  if not image_data:
                      raise ValueError("No image data provided")
                  
                  # Initialize Bedrock client
                  bedrock = get_bedrock_client()
                  
                  # Analyze image
                  analysis_result = analyze_image_with_nova(image_data, bedrock)
                  
                  return analysis_result
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  raise

      Runtime: python3.11
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # Activity Pattern Lambda
  ActivityPatternLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-activity-pattern-${Environment}'
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import json
          
          def get_bedrock_client():
              return boto3.client('bedrock-runtime', region_name='us-east-1')
          
          def analyze_patterns(visual_data, bedrock):
              try:
                  body = json.dumps({
                      "inputText": f"""Based on this visual analysis data: {json.dumps(visual_data)}
                      
                      Provide the analysis in this format:
                      {{
                          "activity_summary": "detailed summary",
                          "timeline": [
                              {{"time": "timestamp", "activity": "description", "duration": "minutes"}}
                          ],
                          "productivity_indicators": {{
                              "focus_time": "percentage",
                              "context_switching": "rate/hour",
                              "active_work_ratio": "percentage"
                          }}
                      }}""",
                      "textGenerationConfig": {
                          "maxTokenCount": 4096,
                          "stopSequences": [],
                          "temperature": 0.7,
                          "topP": 0.8
                      }
                  })
          
                  response = bedrock.invoke_model(
                      modelId="us.amazon.nova-lite-v1:0",
                      body=body
                  )
                  
                  return json.loads(response.get('body').read())
              except Exception as e:
                  print(f"Error in analyze_patterns: {str(e)}")
                  raise
          
          def lambda_handler(event, context):
              try:
                  print("Starting activity pattern analysis")
                  print(f"Event: {json.dumps(event)}")
                  
                  visual_data = event.get('visual_analysis', {})
                  bedrock = get_bedrock_client()
                  
                  pattern_analysis = analyze_patterns(visual_data, bedrock)
                  
                  return pattern_analysis
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  raise

      Runtime: python3.11
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
  # Productivity Assessment Lambda
  ProductivityAssessmentLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-productivity-assessment-${Environment}'
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import json
          
          def get_bedrock_client():
              return boto3.client('bedrock-runtime', region_name='us-east-1')
          
          def assess_productivity(activity_data, bedrock):
              try:
                  body = json.dumps({
                      "inputText": f"""Based on this activity data: {json.dumps(activity_data)}
                      
                      Format the response as:
                      {{
                          "productivity_score": {{
                              "overall": score_0_to_100,
                              "breakdown": {{
                                  "focus": score,
                                  "efficiency": score,
                                  "task_completion": score
                              }}
                          }},
                          "recommendations": [
                              {{
                                  "category": "category",
                                  "suggestion": "detailed suggestion",
                                  "expected_impact": "predicted improvement"
                              }}
                          ],
                          "productivity_metrics": {{
                              "focus_time_ratio": "percentage",
                              "task_switching_cost": "impact",
                              "productive_hours": "number"
                          }}
                      }}""",
                      "textGenerationConfig": {
                          "maxTokenCount": 4096,
                          "stopSequences": [],
                          "temperature": 0.7,
                          "topP": 0.8
                      }
                  })
          
                  response = bedrock.invoke_model(
                      modelId="us.amazon.nova-lite-v1:0",
                      body=body
                  )
                  
                  return json.loads(response.get('body').read())
              except Exception as e:
                  print(f"Error in assess_productivity: {str(e)}")
                  raise
          
          def lambda_handler(event, context):
              try:
                  print("Starting productivity assessment")
                  print(f"Event: {json.dumps(event)}")
                  
                  activity_data = event.get('activity_pattern', {})
                  bedrock = get_bedrock_client()
                  
                  assessment = assess_productivity(activity_data, bedrock)
                  
                  return assessment
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  raise

      Runtime: python3.11
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # Step Functions State Machine
  ProductivityTrackingStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-state-machine-${Environment}'
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Employee Productivity Tracking Workflow",
          "StartAt": "VisualAnalysis",
          "States": {
            "VisualAnalysis": {
              "Type": "Task",
              "Resource": "${VisualAnalysisLambda.Arn}",
              "Next": "ActivityPattern",
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "HandleError"
              }]
            },
            "ActivityPattern": {
              "Type": "Task",
              "Resource": "${ActivityPatternLambda.Arn}",
              "Next": "ProductivityAssessment",
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "HandleError"
              }]
            },
            "ProductivityAssessment": {
              "Type": "Task",
              "Resource": "${ProductivityAssessmentLambda.Arn}",
              "End": true,
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "HandleError"
              }]
            },
            "HandleError": {
              "Type": "Pass",
              "Result": {
                "error": "Workflow execution failed"
              },
              "End": true
            }
          }
        }

  # Step Functions Role
  StepFunctionsExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt VisualAnalysisLambda.Arn
                  - !GetAtt ActivityPatternLambda.Arn
                  - !GetAtt ProductivityAssessmentLambda.Arn

  # API Gateway
  ProductivityAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${AWS::StackName}-api-${Environment}'

  ProductivityResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ProductivityAPI.RootResourceId
      PathPart: 'track'
      RestApiId: !Ref ProductivityAPI

  ProductivityMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ProductivityResource
      RestApiId: !Ref ProductivityAPI
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:states:action/StartExecution'
        Credentials: !GetAtt APIGatewayRole.Arn
        RequestParameters:
          integration.request.header.Content-Type: "'application/x-amz-json-1.0'"
        RequestTemplates:
          application/json: !Sub |
            {
              "input": "$util.escapeJavaScript($input.body)",
              "name": "$context.requestId",
              "stateMachineArn": "${ProductivityTrackingStateMachine}"
            }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: |
                {
                  "executionArn": "$input.path('$.executionArn')",
                  "startDate": "$input.path('$.startDate')"
                }
          - StatusCode: 400
            SelectionPattern: '4\d{2}'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: |
                {
                  "error": "Bad request",
                  "message": $input.path('$.message')
                }
          - StatusCode: 500
            SelectionPattern: '5\d{2}'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: |
                {
                  "error": "Internal server error",
                  "message": $input.path('$.message')
                }
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: 'Empty'
        - StatusCode: 400
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: 'Error'
        - StatusCode: 500
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: 'Error'

  ProductivityOptionsMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
      ResourceId: !Ref ProductivityResource
      RestApiId: !Ref ProductivityAPI

  APIGatewayRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StepFunctionsExecute
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource: !Ref ProductivityTrackingStateMachine

  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: 
      - ProductivityMethod
      - ProductivityOptionsMethod
    Properties:
      RestApiId: !Ref ProductivityAPI

  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    DependsOn: ApiDeployment
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref ProductivityAPI
      StageName: !Ref Environment

  ApiUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn: ApiStage
    Properties:
      ApiStages:
        - ApiId: !Ref ProductivityAPI
          Stage: !Ref Environment
      Description: 'Usage plan for Employee Productivity Tracking API'
      Quota:
        Limit: 1000
        Period: DAY
      Throttle:
        BurstLimit: 10
        RateLimit: 5

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ProductivityAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/track'
  
  StateMachineArn:
    Description: 'Step Functions state machine ARN'
    Value: !Ref ProductivityTrackingStateMachine
  
  ScreenshotBucketName:
    Description: 'S3 bucket for screenshots'
    Value: !Ref ScreenshotBucket

  ApiId:
    Description: 'API Gateway ID'
    Value: !Ref ProductivityAPI

  Region:
    Description: 'AWS Region'
    Value: !Ref 'AWS::Region'

